### ISSUE TITLE
Add Resource Listing

### ISSUE THREAD

**Issue by JakeQuilty** [cyberark/conjur-api-java#69] opened 2020-05-01 17:14 UTC
## Is your feature request related to a problem? Please describe.

Right now The API doesn't have the ability to list the resources in Conjur. To retrieve a secret you have to know the specific name for that secret. Adding the ability to list resources, and parse through them would make it easier to use the API in a more scalable way.

## Describe the solution you would like

[List Resources](https://docs.conjur.org/Latest/en/Content/Developer/Conjur_API_List_Resources.htm)

**Comment by sgnn7** [comment] 2020-05-18 19:55
Duplicate of #52. Closing.

**Closed by sgnn7** 2020-05-18 19:55 UTC
Labels: component/api/java, kind/enhancement
